name: Expentrax CI

on:
  pull_request:
    branches:
      - main
  

jobs:
  style:
    runs-on: ubuntu-latest
    steps:
    # Checkout the code
    - name: Checkout
      uses: actions/checkout@v7.0.1

    # Setup Python
    - name: Setup Python
      uses: actions/setup-python@v7.0.0

    # Install and run ruff check
    - name: ruff-action
      uses: astral-sh/ruff-action@v4.1.0
      run: 'ruff format --check .'
